# Generated by Django 2.2.10 on 2020-02-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='ürün')),
                ('Qty', models.IntegerField(default=0, verbose_name='Adet')),
                ('date_of_purchase', models.DateTimeField(verbose_name='date published')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alış ücreti')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Satış ücreti')),
                ('comment', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
