# Generated by Django 2.2.10 on 2020-02-05 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Ethernet Router', 'Ethernet Router'), ('switch', 'switch'), ('Wireless System', 'Wireless System'), ('Wireless For Home and Office', 'Wireless For Home and Office'), ('LTE Product', 'LTE Product'), ('interface', 'interface'), ('Accessories', 'Accessories')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='date_of_purchase',
            field=models.DateTimeField(verbose_name='Alış tarihi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Alış ücreti'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Satış ücreti'),
        ),
    ]
